- name: criando containers 
  hosts: docker 
  tasks:
   - name: criando volumes do docker
     docker_volume:
      name: "{{item}}"
     with_items:
       - blue
       - green

   - name: criando o container blue e green 
     docker_container:
      name: "{{item.name}}"
      image: "{{item.imagem}}"
      state: started 
      ports:
       - "{{item.port}}:80" 
      volumes: 
       - "{{item.volume}}:/usr/local/apache2/htdocs/"
     with_items: 
      - {name: green, imagem: httpd, volume: green, port: 8787 }
      - {name: blue, imagem: httpd, volume: blue, port: 8788 }
    











